In [52]:
##Importamos librerias
import pandas as pd
import numpy as np
# import matplotlib.pyplot as plt
# import seaborn as sns

In [4]:
#Serie de pandas
numero = [3,4,5,6,7]
serie = pd.Series(numero)
serie, type(serie)

(0    3
 1    4
 2    5
 3    6
 4    7
 dtype: int64,
 pandas.core.series.Series)

In [9]:
#DataFrame
data = {'Nombre': ['Ana', 'Luis', 'Carlos', 'Marta', 'Sofia'],
        'Edad': [25, 30, 35, 28, 22],
        'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Bilbao']}
df = pd.DataFrame(data)
df, type(df)

(   Nombre  Edad     Ciudad
 0     Ana    25     Madrid
 1    Luis    30  Barcelona
 2  Carlos    35   Valencia
 3   Marta    28    Sevilla
 4   Sofia    22     Bilbao,
 pandas.core.frame.DataFrame)

In [16]:
#imprimir el DataFrame
print(data["Nombre"][0])

Ana

In [17]:
#exportar un dataframe a un archivo csv
df.to_csv("datos.csv", index=False)

In [22]:
#importar un archivo csv a un DataFrame
df_importado = pd.read_csv("datos.csv")
df_importado

   Nombre  Edad     Ciudad
0     Ana    25     Madrid
1    Luis    30  Barcelona
2  Carlos    35   Valencia
3   Marta    28    Sevilla
4   Sofia    22     Bilbao

In [21]:
#eliminar columna del DataFrame
df_sin_edad = df_importado.drop("Edad", axis=1)
df_sin_edad

   Nombre     Ciudad
0     Ana     Madrid
1    Luis  Barcelona
2  Carlos   Valencia
3   Marta    Sevilla
4   Sofia     Bilbao

In [24]:
#selecionar una columna del DataFrame
nombres = df_importado["Nombre"]
nombres, type(nombres)

(0       Ana
 1      Luis
 2    Carlos
 3     Marta
 4     Sofia
 Name: Nombre, dtype: object,
 pandas.core.series.Series)

In [25]:
#selecionar varias columnas del DataFrame
nombres_ciudades = df_importado[["Nombre", "Ciudad"]]
nombres_ciudades, type(nombres_ciudades)

(   Nombre     Ciudad
 0     Ana     Madrid
 1    Luis  Barcelona
 2  Carlos   Valencia
 3   Marta    Sevilla
 4   Sofia     Bilbao,
 pandas.core.frame.DataFrame)

In [27]:
#seleccionar filas por indice
fila_0 = df_importado.iloc[0]
fila_0

Nombre       Ana
Edad          25
Ciudad    Madrid
Name: 0, dtype: object

In [29]:
#selecionar por condicion
mayores_25 = df_importado[df_importado["Edad"] > 25]
mayores_25

   Nombre  Edad     Ciudad
1    Luis    30  Barcelona
2  Carlos    35   Valencia
3   Marta    28    Sevilla

In [34]:
#filtrar por nombre que inicia con a o A
filtrar_a = df_importado[df_importado["Nombre"].str.startswith(("a", "A"))]
filtrar_a

  Nombre  Edad  Ciudad
0    Ana    25  Madrid

In [41]:
df_importado

   Nombre  Edad     Ciudad
0     Ana    25     Madrid
1    Luis    30  Barcelona
2  Carlos    35   Valencia
3   Marta    28    Sevilla
4   Sofia    22     Bilbao

In [ ]:
#dos filtros a la vez
FiltrarEdadNombre = (df_importado["Edad"] > 22) & (df_importado["Nombre"].str.startswith(("c", "C")))
filtrar_edad_nombre = df_importado[FiltrarEdadNombre]
filtrar_edad_nombre

   Nombre  Edad    Ciudad
2  Carlos    35  Valencia

In [45]:
#filtrar personas mayores de 22 años query
filtrar_query = df_importado.query("Edad > 22")
filtrar_query

   Nombre  Edad     Ciudad
0     Ana    25     Madrid
1    Luis    30  Barcelona
2  Carlos    35   Valencia
3   Marta    28    Sevilla

In [46]:
#filtrar por nombre especifico query
filtrar_nombre_query = df_importado.query('Nombre == "Ana"')
filtrar_nombre_query

  Nombre  Edad  Ciudad
0    Ana    25  Madrid

In [47]:
#metodo isin para filtrar por una lista de valores
filtrar_ciudades = df_importado[df_importado["Ciudad"].isin(["Madrid", "Sevilla"])]
filtrar_ciudades

  Nombre  Edad   Ciudad
0    Ana    25   Madrid
3  Marta    28  Sevilla

In [49]:
def longCinco(nombre):
    return len(nombre) >= 5

df_importado[df_importado["Nombre"].apply(longCinco)]

   Nombre  Edad    Ciudad
2  Carlos    35  Valencia
3   Marta    28   Sevilla
4   Sofia    22    Bilbao

In [51]:
#filtrar por edades entre 25 y 35 años
#filtrar_edades = df_importado[(df_importado["Edad"] >= 25) & (df_importado["Edad"] <= 35)]
filtrar_edades2 = df_importado[df_importado["Edad"].between(25, 35)]
filtrar_edades2

   Nombre  Edad     Ciudad
0     Ana    25     Madrid
1    Luis    30  Barcelona
2  Carlos    35   Valencia
3   Marta    28    Sevilla

In [74]:
#nuevo data frame
data2 = {'Nombre': ['Ana', 'Luis', 'Carlos', 'Marta', 'Sofia'],
        'Salario': [30000, 40000, 50000, 35000, 32000],
        'edad': [25, 30, np.nan, 28, 22],
        'ciudad': ['Madrid', 'Barcelona', 'Valencia', None, 'Bilbao']
        }
df2 = pd.DataFrame(data2)
df2

   Nombre  Salario  edad     ciudad
0     Ana    30000  25.0     Madrid
1    Luis    40000  30.0  Barcelona
2  Carlos    50000   NaN   Valencia
3   Marta    35000  28.0       None
4   Sofia    32000  22.0     Bilbao

In [64]:
#verificar columnas con valores nulos
df2.isnull().sum()

Nombre     0
Salario    0
edad       1
ciudad     1
dtype: int64

In [66]:
#identificar columnas con valores nulos
columnas_nulas = df2.columns[df2.isnull().any()]
columnas_nulas, type(columnas_nulas)

(Index(['edad', 'ciudad'], dtype='object'), pandas.core.indexes.base.Index)

In [75]:
#rellenar valores nulos con la media de la columna
#media_edad = df2["edad"].mean()
# df2["edad"].fillna(media_edad, inplace=True)
# df2
#media_edad

df_sinNA1 = df2.fillna({
    "Edad": df2["edad"].mean(),
    "ciudad": "Desconocida"
})
df_sinNA1

   Nombre  Salario  edad       ciudad
0     Ana    30000  25.0       Madrid
1    Luis    40000  30.0    Barcelona
2  Carlos    50000   NaN     Valencia
3   Marta    35000  28.0  Desconocida
4   Sofia    32000  22.0       Bilbao

In [77]:
#eliminar filas con valores nulos
df_sinNA2 = df2.dropna()
df_sinNA2

  Nombre  Salario  edad     ciudad
0    Ana    30000  25.0     Madrid
1   Luis    40000  30.0  Barcelona
4  Sofia    32000  22.0     Bilbao

In [82]:
#reemplazar valores especificos de alguna columna
df_reemplazar = df2.replace({"ciudad": {None: "Desconocido","Valencia": "Valencia Capital"}})
df_reemplazar

   Nombre  Salario  edad            ciudad
0     Ana    30000  25.0            Madrid
1    Luis    40000  30.0         Barcelona
2  Carlos    50000   NaN  Valencia Capital
3   Marta    35000  28.0       Desconocido
4   Sofia    32000  22.0            Bilbao

In [83]:
#INTERPOLAR VALORES NUMERICOS
df_interpolar = df2.copy()
df_interpolar["edad"] = df_interpolar["edad"].interpolate(method="linear")
df_interpolar

   Nombre  Salario  edad     ciudad
0     Ana    30000  25.0     Madrid
1    Luis    40000  30.0  Barcelona
2  Carlos    50000  29.0   Valencia
3   Marta    35000  28.0       None
4   Sofia    32000  22.0     Bilbao

In [108]:
#dataframe con valores duplicados
data3 = {'Nombre': ['Ana', 'Luis', 'Carlos', 'Marta', 'Sofia', 'Ana'],
        'Salario': [30000, 40000, 50000, 35000, 32000, 30000],
        'edad': [25, 30, np.nan, 28, 22, 25],
        'ciudad': ['Madrid', 'Barcelona', 'Valencia', None, 'Bilbao', 'Madrid']
        }
df3 = pd.DataFrame(data3)
df3

   Nombre  Salario  edad     ciudad
0     Ana    30000  25.0     Madrid
1    Luis    40000  30.0  Barcelona
2  Carlos    50000   NaN   Valencia
3   Marta    35000  28.0       None
4   Sofia    32000  22.0     Bilbao
5     Ana    30000  25.0     Madrid

In [85]:
#eliminar duplicados
df_sin_duplicados = df3.drop_duplicates()
df_sin_duplicados

   Nombre  Salario  edad     ciudad
0     Ana    30000  25.0     Madrid
1    Luis    40000  30.0  Barcelona
2  Carlos    50000   NaN   Valencia
3   Marta    35000  28.0       None
4   Sofia    32000  22.0     Bilbao

In [101]:
#renombrar columnas
df_renombrado = df3.rename(columns={"Nombre": "name", "Salario": "salary", "edad": "age", "ciudad": "city"})
df_renombrado

     name  salary   age       city
0     Ana   30000  25.0     Madrid
1    Luis   40000  30.0  Barcelona
2  Carlos   50000   NaN   Valencia
3   Marta   35000  28.0       None
4   Sofia   32000  22.0     Bilbao
5     Ana   30000  25.0     Madrid

In [91]:
df4 = df_renombrado.drop_duplicates()
df4

     name  salary   age       city
0     Ana   30000  25.0     Madrid
1    Luis   40000  30.0  Barcelona
2  Carlos   50000   NaN   Valencia
3   Marta   35000  28.0       None
4   Sofia   32000  22.0     Bilbao

In [104]:
#ordenar columna por orden alfabetico
#df_ordenado = df4.sort_values(by="name")
#df3
columnasNuevoOrden = ["Nombre","edad","ciudad","Salario"]
df_ordenado1 = df3[columnasNuevoOrden]
df_ordenado1

   Nombre  edad     ciudad  Salario
0     Ana  25.0     Madrid    30000
1    Luis  30.0  Barcelona    40000
2  Carlos   NaN   Valencia    50000
3   Marta  28.0       None    35000
4   Sofia  22.0     Bilbao    32000
5     Ana  25.0     Madrid    30000

In [113]:
#transformar datos
def edadesCuadrado(edad):
    return edad ** 2

df3["edades_cuadrado"] = df3["edad"].apply(edadesCuadrado)
df3

   Nombre  Salario  edad     ciudad  edades_cuadrado
0     Ana    30000  25.0     Madrid            625.0
1    Luis    40000  30.0  Barcelona            900.0
2  Carlos    50000   NaN   Valencia              NaN
3   Marta    35000  28.0       None            784.0
4   Sofia    32000  22.0     Bilbao            484.0
5     Ana    30000  25.0     Madrid            625.0

In [128]:
#Cargamos el dataset
data = {'nombres': ['Ana', 'Luis', 'Carlos', 'Marta', 'Sofia','Miguel'],
        'ciudad': ['Madrid', 'Barcelona', 'Madrid', 'Sevilla', 'Madrid','Zaragoza'],
        'edades': [25, 30, 35, 28, 22,29],
        'puntuaciones': [85, 90, 95, 88, 92,87]
        }
df5 = pd.DataFrame(data)
df5

  nombres     ciudad  edades  puntuaciones
0     Ana     Madrid      25            85
1    Luis  Barcelona      30            90
2  Carlos     Madrid      35            95
3   Marta    Sevilla      28            88
4   Sofia     Madrid      22            92
5  Miguel   Zaragoza      29            87

In [129]:
#agrupar por ciudad
agrupado = df5.groupby('ciudad')
print(agrupado.groups)

{'Barcelona': [1], 'Madrid': [0, 2, 4], 'Sevilla': [3], 'Zaragoza': [5]}

In [130]:
#calcular suma de edades y puntuaciones por ciudad
dataAgregada = agrupado.agg({'edades': 'mean', 'puntuaciones': 'sum'})
dataAgregada

              edades  puntuaciones
ciudad
Barcelona  30.000000            90
Madrid     27.333333           272
Sevilla    28.000000            88
Zaragoza   29.000000            87

In [132]:
#funciones de agregacion personalizadas
def rangoEdad(serie):
    return serie.max() - serie.min()

#aplicar funcion
dataAgregadaPersonalizada = agrupado.agg({'edades': rangoEdad, 'puntuaciones': rangoEdad})
dataAgregadaPersonalizada

           edades  puntuaciones
ciudad
Barcelona       0             0
Madrid         13            10
Sevilla         0             0
Zaragoza        0             0