In [15]:
import pandas as pd
import numpy as np

In [16]:
data = {
    'Nombre': ['Ana', 'Luis', 'Carlos', 'Marta', 'Jorge'],
    'Edad': [28, 34, 22, 45, 30]
}

In [17]:
df = pd.DataFrame(data)

In [18]:
df

   Nombre  Edad
0     Ana    28
1    Luis    34
2  Carlos    22
3   Marta    45
4   Jorge    30

In [19]:
df['Categoria'] = ['Joven', 'Adulto', 'Joven', 'Adulto', 'Adulto']

In [20]:
df

   Nombre  Edad Categoria
0     Ana    28     Joven
1    Luis    34    Adulto
2  Carlos    22     Joven
3   Marta    45    Adulto
4   Jorge    30    Adulto

In [21]:
df['Ciudades'] = ['Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Bilbao']

In [22]:
df

   Nombre  Edad Categoria   Ciudades
0     Ana    28     Joven     Madrid
1    Luis    34    Adulto  Barcelona
2  Carlos    22     Joven   Valencia
3   Marta    45    Adulto    Sevilla
4   Jorge    30    Adulto     Bilbao

In [29]:
new_row = pd.Series({'Nombre': 'Sofia', 'Edad': 27, 'Categoria': 'Joven', 'Ciudades': 'Granada'})

df = pd.concat([df, new_row.to_frame().T], ignore_index=True)

In [30]:
df

   Nombre Edad Categoria   Ciudades
0     Ana   28     Joven     Madrid
1    Luis   34    Adulto  Barcelona
2  Carlos   22     Joven   Valencia
3   Marta   45    Adulto    Sevilla
4   Jorge   30    Adulto     Bilbao
5   Sofia   27     Joven    Granada
6   Sofia   27     Joven    Granada

In [28]:
new_row.to_frame()

                 0
Nombre       Sofia
Edad            27
Categoria    Joven
Ciudades   Granada