In [9]:
import pandas as pd
import numpy as np

In [33]:
dates = pd.date_range('20230101', periods=12)
dates

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12'],
              dtype='datetime64[ns]', freq='D')

In [35]:
dates.to_numpy()

array(['2023-01-01T00:00:00.000000000', '2023-01-02T00:00:00.000000000',
       '2023-01-03T00:00:00.000000000', '2023-01-04T00:00:00.000000000',
       '2023-01-05T00:00:00.000000000', '2023-01-06T00:00:00.000000000',
       '2023-01-07T00:00:00.000000000', '2023-01-08T00:00:00.000000000',
       '2023-01-09T00:00:00.000000000', '2023-01-10T00:00:00.000000000',
       '2023-01-11T00:00:00.000000000', '2023-01-12T00:00:00.000000000'],
      dtype='datetime64[ns]')

In [36]:
df = pd.DataFrame(
    {
        'A': 1.0,
        'B': pd.Timestamp('20230102'),
        'C': pd.Series(1, index=list(range(4)), dtype='float32'),
        'D': np.array([3] * 4, dtype='int32'),
        'E': pd.Categorical(['test', 'train', 'test', 'train']),
        'F': 'foo'
    }
)
df

     A          B    C  D      E    F
0  1.0 2023-01-02  1.0  3   test  foo
1  1.0 2023-01-02  1.0  3  train  foo
2  1.0 2023-01-02  1.0  3   test  foo
3  1.0 2023-01-02  1.0  3  train  foo

In [37]:
df.to_numpy()

array([[1.0, Timestamp('2023-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2023-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2023-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2023-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [38]:
df.describe()

         A                    B    C    D
count  4.0                    4  4.0  4.0
mean   1.0  2023-01-02 00:00:00  1.0  3.0
min    1.0  2023-01-02 00:00:00  1.0  3.0
25%    1.0  2023-01-02 00:00:00  1.0  3.0
50%    1.0  2023-01-02 00:00:00  1.0  3.0
75%    1.0  2023-01-02 00:00:00  1.0  3.0
max    1.0  2023-01-02 00:00:00  1.0  3.0
std    0.0                  NaN  0.0  0.0

In [14]:
df.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [15]:
dataFrameEjemplo = pd.DataFrame(
    {
        'columna1': pd.Series(1,index=list(range(4)), dtype='float32')
    }
)
dataFrameEjemplo

   columna1
0       1.0
1       1.0
2       1.0
3       1.0

In [54]:
import pandas as pd
import numpy as np

# 1. Tu diccionario de datos
data2 = {
    'Nombre': ['Ana', 'Luis', 'Carlos', 'Marta', 'Sofia'],
    'Salario': [30000, 40000, 50000, 35000, 32000],
    'edad': [25, 30, np.nan, 28, 22],
    'ciudad': ['Madrid', 'Barcelona', 'Valencia', None, 'Bilbao']
}

# 2. Crear el DataFrame
df = pd.DataFrame(data2)

# 3. Agregar el índice como una columna llamada 'Id_Indice'
df['Id_Indice'] = df.index

# Mostrar el resultado
print(df)

   Nombre  Salario  edad     ciudad  Id_Indice
0     Ana    30000  25.0     Madrid          0
1    Luis    40000  30.0  Barcelona          1
2  Carlos    50000   NaN   Valencia          2
3   Marta    35000  28.0       None          3
4   Sofia    32000  22.0     Bilbao          4

In [55]:
columnas = ['Id_Indice', 'Nombre', 'Salario', 'edad', 'ciudad']
df = df[columnas]
print(df)

   Id_Indice  Nombre  Salario  edad     ciudad
0          0     Ana    30000  25.0     Madrid
1          1    Luis    40000  30.0  Barcelona
2          2  Carlos    50000   NaN   Valencia
3          3   Marta    35000  28.0       None
4          4   Sofia    32000  22.0     Bilbao

In [24]:
df.head()

   Id_Indice  Nombre  Salario  edad     ciudad
0          0     Ana    30000  25.0     Madrid
1          1    Luis    40000  30.0  Barcelona
2          2  Carlos    50000   NaN   Valencia
3          3   Marta    35000  28.0       None
4          4   Sofia    32000  22.0     Bilbao

In [61]:
df.loc[0:3,['Nombre', 'Salario']]

   Nombre  Salario
0     Ana    30000
1    Luis    40000
2  Carlos    50000
3   Marta    35000

In [26]:
df.tail(1)

   Id_Indice Nombre  Salario  edad  ciudad
4          4  Sofia    32000  22.0  Bilbao

In [28]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [29]:
df.columns

Index(['Id_Indice', 'Nombre', 'Salario', 'edad', 'ciudad'], dtype='object')

In [30]:
df.to_numpy()

array([[0, 'Ana', 30000, 25.0, 'Madrid'],
       [1, 'Luis', 40000, 30.0, 'Barcelona'],
       [2, 'Carlos', 50000, nan, 'Valencia'],
       [3, 'Marta', 35000, 28.0, None],
       [4, 'Sofia', 32000, 22.0, 'Bilbao']], dtype=object)

In [31]:
df.dtypes

Id_Indice      int64
Nombre        object
Salario        int64
edad         float64
ciudad        object
dtype: object

In [41]:
df = pd.DataFrame({'Datos': [10, 20, 30]}, index=[3, 1, 2])
#df
# Ordena las filas: 1, 2, 3
df_ordenado = df.sort_index()
df_ordenado

   Datos
1     20
2     30
3     10

In [42]:
df_columnas = df.sort_index(axis=1)
df_columnas

   Datos
3     10
1     20
2     30

In [43]:
df_reversa = df.sort_index(ascending=False)
df_reversa

   Datos
3     10
2     30
1     20

In [48]:
df_ciudades = pd.DataFrame({'Población': ['10M', '3M']}, index=['Lima', 'Arequipa'])
#df_ciudades
# 'Arequipa' pasará a la primera fila tras el sort_index()
df_ciudades.sort_index(axis=1)
df_ciudades

         Población
Lima           10M
Arequipa        3M

In [62]:
datos = {
    'Nombre': ['Ana', 'Luis', 'Carlos'],
    'Ciudad': ['Lima', 'Bogotá', 'Santiago']
}
# Usamos códigos personalizados como índice (filas)
df = pd.DataFrame(datos, index=['C-101', 'C-102', 'C-103'])

In [78]:
df

       Nombre    Ciudad
C-101     Ana      Lima
C-102    Luis    Bogotá
C-103  Carlos  Santiago

In [77]:
df.loc['C-101','Nombre']

'Ana'

In [65]:
df.loc['C-102']

Nombre      Luis
Ciudad    Bogotá
Name: C-102, dtype: object

In [67]:
df.loc['C-103', 'Ciudad']

'Santiago'

In [68]:
df.loc['C-101':'C-102', 'Nombre':'Ciudad']

      Nombre  Ciudad
C-101    Ana    Lima
C-102   Luis  Bogotá

In [69]:
df.iloc[0:2, 0:2]

      Nombre  Ciudad
C-101    Ana    Lima
C-102   Luis  Bogotá

In [70]:
df.iloc[0:2]

      Nombre  Ciudad
C-101    Ana    Lima
C-102   Luis  Bogotá