In [17]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'Nombre': ['Ana', 'Luis', 'Carlos'],
    'Ciudad': ['Lima', 'Bogotá', 'Santiago'],
    'Edad': [28, 34, 22],
    'Profesión': ['Ingeniera', 'Médico', 'Estudiante'],
    'Nota': [85, 92, 78]
}

df_data = pd.DataFrame(data)
df_data

   Nombre    Ciudad  Edad   Profesión  Nota
0     Ana      Lima    28   Ingeniera    85
1    Luis    Bogotá    34      Médico    92
2  Carlos  Santiago    22  Estudiante    78

In [9]:
df_data.loc[0:1, 'Nombre':'Ciudad']

  Nombre  Ciudad
0    Ana    Lima
1   Luis  Bogotá

In [11]:
df_data.loc[[0,2], ['Nombre','Ciudad']]

   Nombre    Ciudad
0     Ana      Lima
2  Carlos  Santiago

In [13]:
df_data.iloc[0:2, 0:1
             ]

  Nombre
0    Ana
1   Luis

In [14]:
import pandas as pd

df = pd.DataFrame({'Precio_Base': [100, 250, 50]})

# Aplicamos una función lambda a cada fila de la columna
df['IGV'] = df['Precio_Base'].apply(lambda x: x * 0.18)

print(df)

   Precio_Base   IGV
0          100  18.0
1          250  45.0
2           50   9.0

In [15]:
productos = [('Celular', 15), ('Laptop', 5), ('Tablet', 30)]

# Le decimos a sorted que use como clave de ordenamiento el elemento en la posición 1
productos_ordenados = sorted(productos, key=lambda prod: prod[1])

print(productos_ordenados)

[('Laptop', 5), ('Celular', 15), ('Tablet', 30)]

In [18]:
df = pd.DataFrame(np.random.randn(10, 4))
df

          0         1         2         3
0 -1.284079 -0.162711 -0.530432  0.170630
1 -0.974879 -0.188813 -0.126369 -0.467486
2 -2.098569  0.368710  0.707878 -0.113284
3 -0.664418 -1.397031  0.101161 -0.960298
4 -1.188684 -0.242437 -1.729358 -0.607140
5  0.256064 -0.588689 -1.260394 -0.281729
6  1.440555  0.338446 -1.664477  0.869751
7  0.318306  1.778641  1.039652  0.360929
8 -1.108937  0.658967 -1.350019  0.013736
9  0.942028 -0.601896 -1.227676 -1.289342

In [33]:
df[:3]

          0         1         2         3
0 -1.284079 -0.162711 -0.530432  0.170630
1 -0.974879 -0.188813 -0.126369 -0.467486
2 -2.098569  0.368710  0.707878 -0.113284

In [34]:
df[3:7]

          0         1         2         3
3 -0.664418 -1.397031  0.101161 -0.960298
4 -1.188684 -0.242437 -1.729358 -0.607140
5  0.256064 -0.588689 -1.260394 -0.281729
6  1.440555  0.338446 -1.664477  0.869751

In [37]:
df

          0         1         2         3
0 -1.284079 -0.162711 -0.530432  0.170630
1 -0.974879 -0.188813 -0.126369 -0.467486
2 -2.098569  0.368710  0.707878 -0.113284
3 -0.664418 -1.397031  0.101161 -0.960298
4 -1.188684 -0.242437 -1.729358 -0.607140
5  0.256064 -0.588689 -1.260394 -0.281729
6  1.440555  0.338446 -1.664477  0.869751
7  0.318306  1.778641  1.039652  0.360929
8 -1.108937  0.658967 -1.350019  0.013736
9  0.942028 -0.601896 -1.227676 -1.289342

In [38]:
pieces = [df[:3], df[3:7], df[7:]]
pd.concat(pieces)

          0         1         2         3
0 -1.284079 -0.162711 -0.530432  0.170630
1 -0.974879 -0.188813 -0.126369 -0.467486
2 -2.098569  0.368710  0.707878 -0.113284
3 -0.664418 -1.397031  0.101161 -0.960298
4 -1.188684 -0.242437 -1.729358 -0.607140
5  0.256064 -0.588689 -1.260394 -0.281729
6  1.440555  0.338446 -1.664477  0.869751
7  0.318306  1.778641  1.039652  0.360929
8 -1.108937  0.658967 -1.350019  0.013736
9  0.942028 -0.601896 -1.227676 -1.289342